#!/bin/sh
# Run by github/github codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "$(whoami).*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh $(whoami)
fi
